[package]
name = "prom-attire"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]

[lib]
proc-macro = true

[workspace]
members = ["prom-attire-bootstrap", "prom-attire-impl"]

[dependencies]
error-chain = "0.8.1"
syn = "0.11.4"
prom-attire-bootstrap = { path = "prom-attire-bootstrap" }
prom-attire-impl = { path = "prom-attire-impl" }

[dev_dependencies]
quote = "0.3.12"
