[package]
name = "hats"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]

[lib]
proc-macro = true

[workspace]
members = ["hats-bootstrap", "hats-impl"]

[dependencies]
syn = "0.11.4"
hats-bootstrap = { path = "hats-bootstrap" }
hats-impl = { path = "hats-impl" }
